### ISSUE TITLE
"Today I Learned" 클릭 시 최신글 목록으로 이동

### ISSUE THREAD

**Issue by stovecat** [webdonalds/til.webdonalds.org#7]
게시글 페이지에서 "<- 최신글 목록"이 너무 작아서 그런지  Today I Learned를 클릭하게 됨

**Comment by hellodhlyn** [comment]
요런식으로 대메뉴를 하나 만들까 고민중

![image](https://user-images.githubusercontent.com/8597749/153577280-b961072f-b81d-4d54-bf35-180f242dfdd5.png)

**Comment by hellodhlyn** [comment]
resolved by a74652f0a14c77edc4b5e73e60239613c6803d62
